---
title: "Text mining: model Bag of Words"
author: ""
date: ""
output:
   html_document:
     df_print: paged
     theme: cerulean
     highlight: default
     toc: yes
     toc_depth: 3
     toc_float:
        collapsed: false
        smooth_scroll: true
     code_fold: show
---

```{r}
knitr::opts_chunk$set(
  message = FALSE,
  warning = FALSE
)


# install.packages(c("tm", "tidytext", "stringr", "wordcloud", "RColorBrewer", "ggplot2", "SnowballC", "SentimentAnalysis", "ggthemes",  "tidyverse", "rmarkdown"))
# install.packages("knitr")
```

# Wymagane pakiety

```{r}
# Wymagane pakiety ----
library(tm)
library(tidytext)
library(stringr)
library(wordcloud)
library(RColorBrewer)
library(ggplot2)
library(SnowballC)
library(SentimentAnalysis)
library(ggthemes)
library(tidyverse)
library(rmarkdown)
library(knitr)
```

# 0. Funkcja do przetwarzania tekstu z apostrofami, stemmingiem i stemCompletion

```{r}
# 0. Funkcja do przetwarzania tekstu z apostrofami, stemmingiem i stemCompletion ----
process_text <- function(file_path) {
  text <- tolower(readLines(file_path, encoding = "UTF-8"))
  text <- gsub("[\u2019\u2018\u0060\u00B4]", "'", text)
  text <- removeNumbers(text)
  words <- unlist(strsplit(text, "\\s+"))
  words <- words[words != ""]
  words <- words[!str_detect(words, "'")]
  words <- str_replace_all(words, "[[:punct:]]", "")
  words <- words[words != ""]
  words <- str_trim(words)
  
  tidy_stopwords <- tolower(stop_words$word)
  tidy_stopwords <- gsub("[\u2019\u2018\u0060\u00B4]", "'", tidy_stopwords)
  tm_stopwords <- tolower(stopwords("en"))
  tm_stopwords <- gsub("[\u2019\u2018\u0060\u00B4]", "'", tm_stopwords)
  
  words <- words[!(words %in% tidy_stopwords)]
  words <- words[!(words %in% tm_stopwords)]
  
  # Stemming + stem completion
  stemmed_doc <- stemDocument(words)
  completed_doc <- stemCompletion(stemmed_doc, dictionary=words, type="prevalent")
  completed_doc <- completed_doc[completed_doc != ""]
  
  return(completed_doc)
}



#' # 0. Funkcja do obliczania cz?sto?ci wyst?powania s??w
# 0. Funkcja do obliczania cz?sto?ci wyst?powania s??w ----
word_frequency <- function(words) {
  freq <- table(words)
  freq_df <- data.frame(word = names(freq), freq = as.numeric(freq))
  freq_df <- freq_df[order(-freq_df$freq), ]
  return(freq_df)
}



#' # 0. Funkcja do tworzenia chmury s??w 
# 0. Funkcja do tworzenia chmury s??w ----
plot_wordcloud <- function(freq_df, title, color_palette = "Dark2") {
  wordcloud(words = freq_df$word, freq = freq_df$freq, min.freq = 16,
            colors = brewer.pal(8, color_palette))
  title(title)
}
```

# ANALIZA TEXT MINING

```{r}
# ANALIZA TEXT MINING ----
```

#### ???? Przetwarzanie i oczyszczanie tekstu <br>*(Text Preprocessing and Text Cleaning)*

- wczytanie tekstu z odpowiednim kodowaniem (UTF-8)

```{r}
#' - normalizacja (ujednolicenie) wielko?ci liter (zamiana na ma?e litery = lowercase)
#' - normalizacja (ujednolicenie) rozbie?nych kodowa? znak?w (apostrofy, cudzys?owy)
#' - normalizacja (ujednolicenie) form skr?conych (I'm, I've, don't) przez usuni?cie lub rozwini?cie
#' - normalizacja (ujednolicenie) r??nych akcent?w ("caf?" na "cafe") przez usuni?cie akcent?w
#' - normalizacja (ujednolicenie) popularnych skr?t?w ("btw" na "by the way", "b4" na "before") przez rozwini?cie
#' - usuni?cie zb?dnych ci?g?w znak?w (adresy URL, tagi HTML)
#' - usuni?cie zb?dnych znak?w specjalnych (*, &, #, @, $)
#' - usuni?cie zb?dnych bia?ych znak?w (spacja, tabulacja, znak przej?cia do nowej linii "enter")
#' - usuni?cie cyfr i liczb
#' - usuni?cie interpunkcji
#' - tokenizacja (podzia? tekstu na s?owa = tokeny)
#' - usuni?cie stopwords (s??w o ma?ej warto?ci semantycznej, np. "the", "and")
#' - usuni?cie pustych element?w (rozwa?enie problemu brakuj?cych/niekompletnych danych )
#' - stemming lub lematyzacja (sprowadzenie s??w do ich rdzenia/formy podstawowej)
```



```{r}
#' #### ???? Zliczanie cz?sto?ci s??w <br>*(Word Frequency Count)*
```



```{r}
#' #### ???? Eksploracyjna analiza danych: <br>wizualizacja cz?sto?ci s??w (tabela, wykres, chmura s??w) <br>*(Exploratory Data Analysis, EDA)*
```



```{r}
#' #### ???? In?ynieria cech w modelu Bag of Words: <br>reprezentacja tekstu jako zbioru s??w i cz?sto?ci s??w ( = cechy) <br>*(Feature Engineering in BoW model)*
```



```{r}
# Wczytanie i przetworzenie tekstu ----
# file_path <- "sciezka/do/pliku.txt"  <= Uzupe?nij nazw? pliku i ustaw Working Directory!
file_path <- "Trump.txt"
words <- process_text(file_path)

# Dodatkowe niestandardowe stopwords
custom_stopwords <- c("$")
words <- words[!words %in% custom_stopwords]

# Cz?sto?? s??w
freq_df <- word_frequency(words)

# Chmura s??w
plot_wordcloud(freq_df, "Chmura s??w", "Dark2")

# Wy?wietl top 10
print(head(freq_df, 10))




#' # Analiza sentymentu s?owniki CSV
# Analiza sentymentu s?owniki CSV ----



#' # Wczytaj s?owniki z plik?w csv
# Wczytaj s?owniki z plik?w csv ----
afinn <- read.csv("afinn.csv", stringsAsFactors = FALSE)
bing <- read.csv("bing.csv", stringsAsFactors = FALSE)
loughran <- read.csv("loughran.csv", stringsAsFactors = FALSE)
nrc <- read.csv("nrc.csv", stringsAsFactors = FALSE)


tidy_tokeny <- as_tibble(freq_df)



#' # Analiza sentymentu przy u?yciu s?ownika Loughran
# Analiza sentymentu przy u?yciu s?ownika Loughran ----

# U?ycie inner_join()
tidy_tokeny %>%
  inner_join(loughran, relationship = "many-to-many")
# Liczba s??w drastycznie si? zmniejszy?a,
# poniewa? inner_join zachowa? tylko te s?owa,
# kt?re wyst?powa?y w s?owniku


# Zliczanie sentymentu
sentiment_review <- tidy_tokeny %>%
  inner_join(loughran, relationship = "many-to-many")

sentiment_review %>%
  count(sentiment)


# Zliczanie, kt?re s?owa s? najcz?stsze
# dla danego sentymentu
sentiment_review %>%
  group_by(sentiment) %>%
  arrange(desc(freq)) %>%
  ungroup()

# Filtrowanie analizy sentymentu
# i pozostawienie tylko s??w
# o sentymencie pozytywnym lub negatywnym

sentiment_review2 <- sentiment_review %>%
  filter(sentiment %in% c("positive", "negative"))


word_counts <- sentiment_review2 %>%
  group_by(sentiment) %>%
  top_n(20, freq) %>%
  ungroup() %>%
  arrange(desc(freq), word) %>%
  mutate(
    word2 = factor(word, levels = rev(unique(word)))
  )

# Wizualizacja sentymentu
ggplot(word_counts[1:30,], aes(x=word2, y=freq, fill=sentiment)) + 
  geom_col(show.legend=FALSE) +
  facet_wrap(~sentiment, scales="free") +
  coord_flip() +
  labs(x = "S?owa", y = "Liczba") +
  theme_gdocs() + 
  ggtitle("Liczba s??w wg sentymentu (Loughran)") +
  scale_fill_manual(values = c("firebrick", "darkolivegreen4"))



#' # Analiza sentymentu przy u?yciu s?ownika NRC
# Analiza sentymentu przy u?yciu s?ownika NRC ----


# Zliczanie sentymentu
sentiment_review_nrc <- tidy_tokeny %>%
  inner_join(nrc, relationship = "many-to-many")

sentiment_review_nrc %>%
  count(sentiment)

# Zliczanie, kt?re s?owa s? najcz?stsze
# dla danego sentymentu
sentiment_review_nrc %>%
  group_by(sentiment) %>%
  arrange(desc(freq)) %>%
  ungroup()

# Filtrowanie analizy sentymentu
# i pozostawienie tylko s??w
# o sentymencie pozytywnym lub negatywnym

sentiment_review_nrc2 <- sentiment_review_nrc %>%
  filter(sentiment %in% c("positive", "negative"))


word_counts_nrc2 <- sentiment_review_nrc2 %>%
  group_by(sentiment) %>%
  top_n(20, freq) %>%
  ungroup() %>%
  arrange(desc(freq), word) %>%
  mutate(
    word2 = factor(word, levels = rev(unique(word)))
  )

# Wizualizacja sentymentu
ggplot(word_counts_nrc2[1:30,], aes(x=word2, y=freq, fill=sentiment)) + 
  geom_col(show.legend=FALSE) +
  facet_wrap(~sentiment, scales="free") +
  coord_flip() +
  labs(x = "S?owa", y = "Liczba") +
  theme_gdocs() + 
  ggtitle("Liczba s??w wg sentymentu (NRC)")



#' # Analiza sentymentu przy u?yciu s?ownika Bing
# Analiza sentymentu przy u?yciu s?ownika Bing ----


# Zliczanie sentymentu
sentiment_review_bing <- tidy_tokeny %>%
  inner_join(bing)

sentiment_review_bing %>%
  count(sentiment)

# Zliczanie, kt?re s?owa s? najcz?stsze
# dla danego sentymentu
sentiment_review_bing %>%
  group_by(sentiment) %>%
  arrange(desc(freq)) %>%
  ungroup()

# Filtrowanie analizy sentymentu
# i pozostawienie tylko s??w
# o sentymencie pozytywnym lub negatywnym

sentiment_review_bing2 <- sentiment_review_bing %>%
  filter(sentiment %in% c("positive", "negative"))


word_counts_bing2 <- sentiment_review_bing2 %>%
  group_by(sentiment) %>%
  top_n(20, freq) %>%
  ungroup() %>%
  arrange(desc(freq), word) %>%
  mutate(
    word2 = factor(word, levels = rev(unique(word)))
  )

# Wizualizacja sentymentu
ggplot(word_counts_bing2[1:30,], aes(x=word2, y=freq, fill=sentiment)) + 
  geom_col(show.legend=FALSE) +
  facet_wrap(~sentiment, scales="free") +
  coord_flip() +
  labs(x = "S?owa", y = "Liczba") +
  theme_gdocs() + 
  ggtitle("Liczba s??w wg sentymentu (Bing)") +
  scale_fill_manual(values = c("dodgerblue4", "goldenrod1"))



#' # Analiza sentymentu przy u?yciu s?ownika Afinn
# Analiza sentymentu przy u?yciu s?ownika Afinn ----


# Zliczanie sentymentu
sentiment_review_afinn <- tidy_tokeny %>%
  inner_join(afinn)

sentiment_review_afinn %>%
  count(value)

# Zliczanie, kt?re s?owa s? najcz?stsze
# dla danego sentymentu
sentiment_review_afinn %>%
  group_by(value) %>%
  arrange(desc(freq)) %>%
  ungroup()

# Silnie pozytywne lub silnie negatywne s?owa:
# filtrowanie analizy sentymentu
# i pozostawienie tylko s??w o warto?ci w zakresie od -5 do 5

sentiment_review_afinn3 <- sentiment_review_afinn %>%
  filter(value %in% c("3", "-3" , "4", "-4", "5", "-5"))


word_counts_afinn3 <- sentiment_review_afinn3 %>%
  group_by(value) %>%
  top_n(20, freq) %>%
  ungroup() %>%
  arrange(desc(freq), word) %>%
  mutate(
    word2 = factor(word, levels = rev(unique(word)))
  )

# Wizualizacja sentymentu
ggplot(word_counts_afinn3[1:30,], aes(x=word2, y=freq, fill=value)) + 
  geom_col(show.legend=FALSE) +
  facet_wrap(~value, scales="free") +
  coord_flip() +
  labs(x = "S?owa", y = "Liczba") +
  theme_gdocs() + 
  ggtitle("Liczba s??w wg sentymentu (AFINN)")





#' # Analiza sentymentu w czasie o ustalonej d?ugo?ci linii
# Analiza sentymentu w czasie o ustalonej d?ugo?ci linii ----



# Po??czenie wszystkich s??w words w jeden ci?g znak?w
full_text <- paste(words, collapse = " ")


# Funkcja do dzielenia tekstu na segmenty o okre?lonej d?ugo?ci
split_text_into_chunks <- function(text, chunk_size) {
  start_positions <- seq(1, nchar(text), by = chunk_size)
  chunks <- substring(text, start_positions, start_positions + chunk_size - 1)
  return(chunks)
}


# Podzielenie tekstu na segmenty
#
# ustaw min_lentgh jako jednolit? d?ugo?? jednego segmentu
set_length <- 50
text_chunks <- split_text_into_chunks(full_text, set_length)


# Wy?wietlenie wynikowych segment?w
# print(text_chunks)



#' # Analiza sentymentu przy u?yciu pakietu SentimentAnalysis
# Analiza sentymentu przy u?yciu pakietu SentimentAnalysis ----
sentiment <- analyzeSentiment(text_chunks)



#' # S?ownik GI (General Inquirer)
### S?ownik GI (General Inquirer) ----
#
# S?ownik og?lnego zastosowania
# zawiera list? s??w pozytywnych i negatywnych
# zgodnych z psychologicznym s?ownikiem harwardzkim Harvard IV-4
# DictionaryGI


# Wczytaj s?ownik GI
# data(DictionaryGI)
# summary(DictionaryGI)


# Konwersja ci?g?ych warto?ci sentymentu 
# na odpowiadaj?ce im warto?ci kierunkowe 
# zgodnie ze s?ownikiem GI
sentimentGI <- convertToDirection(sentiment$SentimentGI)


# Wykres skumulowanego sentymentu kierunkowego
#plot(sentimentGI)


# Ten sam wykres w ggplot2:
# Konwersja do ramki danych (ggplot wizualizuje ramki danych)
df_GI <- data.frame(index = seq_along(sentimentGI), value = sentimentGI, Dictionary = "GI")

# Usuni?cie wierszy, kt?re zawieraj? NA
df_GI <- na.omit(df_GI)

ggplot(df_GI, aes(x = value)) +
  geom_bar(fill = "green", alpha = 0.7) + 
  labs(title = "Skumulowany sentyment (GI)",
       x = "Sentyment",
       y = "Liczba") +
  theme_bw()




#' # S?ownik HE (Henry?s Financial dictionary)
### S?ownik HE (Henry?s Financial dictionary) ----
#
# zawiera list? s??w pozytywnych i negatywnych
# zgodnych z finansowym s?ownikiem "Henry 2008"
# pierwszy, jaki powsta? w wyniku analizy komunikat?w prasowych 
# dotycz?cych zysk?w w bran?y telekomunikacyjnej i us?ug IT
# DictionaryHE


# Wczytaj s?ownik HE
# data(DictionaryHE)
# summary(DictionaryHE)


# Konwersja ci?g?ych warto?ci sentymentu 
# na odpowiadaj?ce im warto?ci kierunkowe 
# zgodnie ze s?ownikiem HE
sentimentHE <- convertToDirection(sentiment$SentimentHE)


# Wykres skumulowanego sentymentu kierunkowego
# plot(sentimentHE)


# Ten sam wykres w ggplot2:
# Konwersja do ramki danych (ggplot wizualizuje ramki danych)
df_HE <- data.frame(index = seq_along(sentimentHE), value = sentimentHE, Dictionary = "HE")

# Usuni?cie wierszy, kt?re zawieraj? NA
df_HE <- na.omit(df_HE)

ggplot(df_HE, aes(x = value)) +
  geom_bar(fill = "blue", alpha = 0.7) + 
  labs(title = "Skumulowany sentyment (HE)",
       x = "Sentyment",
       y = "Liczba") +
  theme_bw()




#' # S?ownik LM (Loughran-McDonald Financial dictionary)
### S?ownik LM (Loughran-McDonald Financial dictionary) ----
#
# zawiera list? s??w pozytywnych i negatywnych oraz zwi?zanych z niepewno?ci?
# zgodnych z finansowym s?ownikiem Loughran-McDonald
# DictionaryLM


# Wczytaj s?ownik LM
# data(DictionaryLM)
# summary(DictionaryLM)


# Konwersja ci?g?ych warto?ci sentymentu 
# na odpowiadaj?ce im warto?ci kierunkowe 
# zgodnie ze s?ownikiem LM
sentimentLM <- convertToDirection(sentiment$SentimentLM)


# Wykres skumulowanego sentymentu kierunkowego
# plot(sentimentLM)


# Ten sam wykres w ggplot2:
# Konwersja do ramki danych (ggplot wizualizuje ramki danych)
df_LM <- data.frame(index = seq_along(sentimentLM), value = sentimentLM, Dictionary = "LM")

# Usuni?cie wierszy, kt?re zawieraj? NA
df_LM <- na.omit(df_LM)

ggplot(df_LM, aes(x = value)) +
  geom_bar(fill = "orange", alpha = 0.7) + 
  labs(title = "Skumulowany sentyment (LM)",
       x = "Sentyment",
       y = "Liczba") +
  theme_bw()




#' # S?ownik QDAP (Quantitative Discourse Analysis Package)
### S?ownik QDAP (Quantitative Discourse Analysis Package) ----
#
# zawiera list? s??w pozytywnych i negatywnych
# do analizy dyskursu


# Wczytaj s?ownik QDAP
qdap <- loadDictionaryQDAP()
# summary(qdap)


# Konwersja ci?g?ych warto?ci sentymentu 
# na odpowiadaj?ce im warto?ci kierunkowe 
# zgodnie ze s?ownikiem QDAP
sentimentQDAP <- convertToDirection(sentiment$SentimentQDAP)


# Wykres skumulowanego sentymentu kierunkowego
# plot(sentimentQDAP)


# Ten sam wykres w ggplot2:
# Konwersja do ramki danych (ggplot wizualizuje ramki danych)
df_QDAP <- data.frame(index = seq_along(sentimentQDAP), value = sentimentQDAP, Dictionary = "QDAP")

# Usuni?cie wierszy, kt?re zawieraj? NA
df_QDAP <- na.omit(df_QDAP)

ggplot(df_QDAP, aes(x = value)) +
  geom_bar(fill = "red", alpha = 0.7) + 
  labs(title = "Skumulowany sentyment (QDAP)",
       x = "Sentyment",
       y = "Liczba") +
  theme_bw()



#' # Por?wnanie sentymentu na podstawie r??nych s?ownik?w
# Por?wnanie sentymentu na podstawie r??nych s?ownik?w ----

# Minimalistycznie
# plot(convertToDirection(sentiment$SentimentGI))
# plot(convertToDirection(sentiment$SentimentHE))
# plot(convertToDirection(sentiment$SentimentLM))
# plot(convertToDirection(sentiment$SentimentQDAP))


# Wizualnie lepsze w ggplot2
# Po??czenie poszczeg?lnych ramek w jedn? ramk?
df_all <- bind_rows(df_GI, df_HE, df_LM, df_QDAP)

# Tworzenie wykresu z podzia?em na s?owniki
ggplot(df_all, aes(x = value, fill = Dictionary)) +
  geom_bar(alpha = 0.7) + 
  labs(title = "Skumulowany sentyment wed?ug s?ownik?w",
       x = "Sentyment",
       y = "Liczba") +
  theme_bw() +
  facet_wrap(~Dictionary) +  # Podzia? na cztery osobne wykresy
  scale_fill_manual(values = c("GI" = "green", 
                               "HE" = "blue", 
                               "LM" = "orange",
                               "QDAP" = "red" ))





#' # Agregowanie sentymentu z r??nych s?ownik?w w czasie
# Agregowanie sentymentu z r??nych s?ownik?w w czasie ----


# Sprawdzenie ilo?ci obserwacji
length(sentiment[,1])


# Utworzenie ramki danych
df_all <- data.frame(sentence=1:length(sentiment[,1]),
                     GI=sentiment$SentimentGI, 
                     HE=sentiment$SentimentHE, 
                     LM=sentiment$SentimentLM,
                     QDAP=sentiment$SentimentQDAP)



# USUNI?CIE BRAKUJ?CYCH WARTO?CI
# gdy? warto?ci NA (puste) uniemo?liwiaj? generowanie wykresu w ggplot
#

# Usuni?cie warto?ci NA
# Wybranie tylko niekompletnych przypadk?w:
puste <- df_all[!complete.cases(df_all), ]


# Usuni?cie pustych obserwacji
# np. dla zmiennej QDAP (wszystkie maj? NA)
df_all <- df_all[!is.na(df_all$QDAP), ]


# Sprawdzenie, czy warto?ci NA zosta?y usuni?te
# wtedy puste2 ma 0 wierszy:
puste2 <- df_all[!complete.cases(df_all), ]
puste2




#' # Wykresy przedstawiaj?ce ewolucj? sentymentu w czasie
# Wykresy przedstawiaj?ce ewolucj? sentymentu w czasie ----



ggplot(df_all, aes(x=sentence, y=QDAP)) +
  geom_line(color="red", size=1) +
  geom_line(aes(x=sentence, y=GI), color="green", size=1) +
  geom_line(aes(x=sentence, y=HE), color="blue", size=1) +
  geom_line(aes(x=sentence, y=LM), color="orange", size=1) +
  labs(x = "O? czasu zda?", y = "Sentyment") +
  theme_gdocs() + 
  ggtitle("Zmiana sentymentu w czasie")



ggplot(df_all, aes(x=sentence, y=QDAP)) + 
  geom_smooth(color="red") +
  geom_smooth(aes(x=sentence, y=GI), color="green") +
  geom_smooth(aes(x=sentence, y=HE), color="blue") +
  geom_smooth(aes(x=sentence, y=LM), color="orange") +
  labs(x = "O? czasu zda?", y = "Sentyment") +
  theme_gdocs() + 
  ggtitle("Zmiana sentymentu w czasie")
```

